---
title: "Untitled"
author: "Dominic Contreras"
date: "September 4, 2018"
output: html_document
---

```{r setup, include=FALSE}
# Class 4 ggplot2 Examples
require(ggplot2)
require(plotly)
library(knitr)
opts_chunk$set(fig.width=12, fig.height=8, fig.path='Figs/')

# Data Stuff
require(dplyr)
require(tibble)
require(reshape2)
require(scales)
library(RColorBrewer)
require(RColorBrewer)

pdf(NULL) # makes sure plotly does not break

diamonds <- diamonds
mtcars <- mtcars %>% # makes rownames a column
  rownames_to_column() 
iris <- iris
starwars <- starwars
airquality <- airquality %>%
  mutate(Date = as.Date(paste0("1973-", Month, "-", Day)))
```

```{r bar}
ggplot(data = diamonds, aes(cut, fill = cut)) +
  geom_bar(stat = "count") +
  scale_y_continuous (labels = comma) +
  ggtitle("Count of Diamonds by Cut") +
  xlab("Cut") +
  ylab("Count of Diamonds") +
  scale_fill_brewer(palette = "Set1")
```

```{r bar}
ggplot(data = diamonds, aes(cut, color = cut)) +
  geom_bar(stat = "count") +
  scale_y_continuous (labels = comma) +
  ggtitle("Count of Diamonds by Cut") +
  xlab("Cut") +
  ylab("Count of Diamonds") +
  scale_color_brewer(palette = "Set1")
```

```{r}
ggplot(data = mtcars, aes(x = hp, y = drat, color = as.factor(cyl))) +
  geom_point() +
  scale_color_brewer(palette = "Oranges")
```

```{r}
ggplot(data = mtcars, aes(x = hp, y = drat, color = as.factor(cyl))) +
  geom_point() +
  scale_color_brewer(palette = "Oranges") +
  facet_wrap(~as.factor(gear))
```

```{r}
ggplot(data = mtcars, aes(x = hp, y = drat, color = as.factor(cyl))) +
  geom_point() +
  scale_color_brewer(palette = "Oranges") +
  geom_hline(yintercept = mean(mtcars$drat), color = "magenta") +
  geom_label(x = 200, y = mean(mtcars$drat), label = paste("Avg Drat:", mean(mtcars$drat)))
```

```{r}
ggplot(mtcars, aes(x = hp, y = mpg)) + 
  geom_point() + 
  geom_text(aes(label = rowname), angle = 45, hjust = 0, vjust = 0, nudge_y = .5)
```

```{r}
ggplotly(
  ggplot(data = airquality, aes(x = Date, y = Wind, group = 1, text = paste("<b>", format(Date, "%B %d"), "</b>: ", Wind))) +
    geom_point() +
    geom_line(),
  tooltip = "text"
  )
```

